# Default values for nacos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imageRegistry: "docker.io"

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 3

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: nacos/nacos-server
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# MySQL configuration
mysql:
  host: "my-mysql-innodbcluster.test-job"
  port: "3306"
  database: "nacos_data"
  username: "root"
  password: "root"
