apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nacos.fullname" . }}-mysql-config
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
data:
  MYSQL_SERVICE_HOST: {{ .Values.mysql.host | quote }}
  MYSQL_SERVICE_PORT: {{ .Values.mysql.port | quote }}
  MYSQL_SERVICE_DB_NAME: {{ .Values.mysql.database | quote }}
  MYSQL_SERVICE_USER: {{ .Values.mysql.username | quote }}
  MYSQL_SERVICE_PASSWORD: {{ .Values.mysql.password | quote }}
