kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ include "nacos.name" . }}
  labels:
    app: {{ include "nacos.name" . }}
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nacos.name" . }}
      {{- include "nacos.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "nacos.headlessService" . }}
  template:
    metadata:
      labels:
        app: {{ include "nacos.name" . }}
        {{- include "nacos.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "nacos.name" . }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8848
              protocol: TCP
            - name: grpc
              containerPort: 9848
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "nacos.fullname" . }}-mysql-config
          env:
            - name: MODE
              value: "cluster"
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: CLUSTER_DOMAIN
              value: "cluster.local"
            - name: SERVICE_NAME
              value: nacos-headless
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_SERVER_GRPC_PORT
              value: "9848"
            - name: NACOS_SERVER_GRPC_PORT_OFFSET
              value: "1000"
            - name: NACOS_AUTH_ENABLE
              value: {{ .Values.auth.enabled | quote }}
            - name: NACOS_AUTH_TOKEN
              value: {{ include "nacos.authKey" . | quote }}
            - name: NACOS_AUTH_IDENTITY_KEY
              value: {{ include "nacos.authKey" . | quote }}
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: {{ include "nacos.authKey" . | quote }}
            - name: NACOS_SERVERS
              value: "{{- range $i, $e := until (.Values.replicaCount | int) }}{{ if $i }} {{ end }}{{ include "nacos.fullname" $ }}-{{ $i }}.{{ include "nacos.headlessService" $ }}.{{ $.Release.Namespace }}.svc.cluster.local:8848{{- end }}"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
